version: '3.5'
services:
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sock:/run/sock
    depends_on:
      - faiss1
      - faiss2
      - faiss3
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '20MB'
        reservations:
          cpus: '0.1'
          memory: '20MB'
    networks:
      - rinha

  faiss1: &faiss
    build:
      context: ./python/
    image: fraud-faiss-api
    platform: linux/x86_64
    hostname: faiss1
    restart: always
    volumes:
      - sock:/run/sock
    environment:
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
    command: >
      uvicorn main:app
      --uds /run/sock/uvicorn1.sock
      --loop uvloop
      --http httptools
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '110MB'
        reservations:
          cpus: '0.3'
          memory: '110MB'
    networks:
      - rinha

  faiss2:
    <<: *faiss
    hostname: faiss2
    command: >
      uvicorn main:app
      --uds /run/sock/uvicorn2.sock
      --loop uvloop
      --http httptools
  
  faiss3:
    <<: *faiss
    hostname: faiss3
    command: >
      uvicorn main:app
      --uds /run/sock/uvicorn3.sock
      --loop uvloop
      --http httptools

volumes:
  sock:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,mode=0777"

networks:
  rinha:
    driver: bridge