worker_processes 3;
worker_rlimit_nofile 500000;

events {
  use epoll;
  worker_connections 10000;
  multi_accept on;
}

http {
  log_format  main  '"$time_local" '
                    'method=$request_method request="$request" '
                    'request_length=$request_length '
                    'status=$status bytes_sent=$bytes_sent '
                    'body_bytes_sent=$body_bytes_sent '
                    'upstream_addr=$upstream_addr '
                    'upstream_status=$upstream_status '
                    'request_time=$request_time '
                    'upstream_response_time=$upstream_response_time '
                    'upstream_connect_time=$upstream_connect_time '
                    'upstream_header_time=$upstream_header_time';

  access_log /var/log/nginx/access.log main;
  # access_log off;

  reset_timedout_connection on;
  proxy_read_timeout 300;
  proxy_connect_timeout 300;
  proxy_send_timeout 300;

  upstream api {
    server faiss1:8080;
    server faiss2:8080;
    keepalive 200;
  }

  server {
    listen 9999 http2;

    location / {
      proxy_buffering on;
      proxy_set_header Connection "";
      proxy_http_version 1.1;
      proxy_set_header Keep-Alive "";
      proxy_set_header Proxy-Connection "keep-alive";
      proxy_pass http://api;
    }
  }
}
